plugins {
    `java-library`
    id("com.jfrog.artifactory") version "5.1.10"
}

version = System.getenv("SHORT_COMMIT_HASH") ?: "dev"

allprojects {
    apply(plugin = "java")

    group = "net.minestom"
    version = rootProject.version

    repositories {
        mavenCentral()
        maven(url = "https://jitpack.io")
    }

    tasks.withType<JavaCompile>().configureEach {
        options.encoding = "UTF-8"
    }

    configurations.all {
        // We only use Jetbrains Annotations
        exclude("org.checkerframework", "checker-qual")
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType<Zip> {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }

    tasks.withType<Test> {
        useJUnitPlatform()

        // Viewable packets make tracking harder. Could be re-enabled later.
        jvmArgs("-Dminestom.viewable-packet=false")
        jvmArgs("-Dminestom.inside-test=true")
    }
}

sourceSets {
    main {
        java.srcDir(file("src/main/java"))
        java.srcDir(file("src/autogenerated/java"))
    }
}

dependencies {
    api(libs.slf4j)
    api(libs.jetbrainsAnnotations)
    api(libs.bundles.adventure)
    api(libs.hydrazine)
    api(libs.bundles.kotlin)
    api(libs.bundles.hephaistos)
    api(libs.dependencyGetter)
    implementation(libs.minestomData)
    implementation(libs.caffeine)
    api(libs.fastutil)
    implementation(libs.bundles.flare)
    api(libs.gson)
    implementation(libs.jcTools)
    testImplementation(libs.bundles.junit)
}

artifactory {
    setContextUrl("https://artifactory.bytemc.de/artifactory/bytemc-public/")

    publish {
        repository {
            username = "mirco"
            password = "Polo123.#"
            repoKey = "bytemc-public"
        }
    }
}