name: Build and deploy Javadoc

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build javadoc
      run: ./gradlew javadoc
      
    - name: Deploy javadocs
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:hollow-cube/javadocs.git
        BRANCH: main
        FOLDER: build/docs/javadoc
        TARGET_DIR: minestom-ce
        SSH_PRIVATE_KEY: ${{ secrets.JAVADOC_DEPLOY_PRIVATE_KEY }}
        CLEAR_GLOBS_FILE: ".github/javadoc-publish-clear"
